############### Inicio de sención ###############################
POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
  "nombre_email": "pep@example.com",
  "contrasena": "hoalpass"
}

###
POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
  "nombre_email": "manF@example.com",
  "contrasena": "hoalpass"
}

###


###eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTE2NTQ0MywiZXhwIjoxNzY5MTY5MDQzfQ.U2Cb07JakEtrvICKd-Ch3J8xS1_4vRJ_5EqXZZdvda0
POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
"nombre_email": "juanF@example.com",
"contrasena": "hoalpass"
}

############### ACTIVIDAD ###############################
### Crear actividad
POST http://localhost:3000/api/actividad
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc3MjAxMzg4OSwiZXhwIjoxNzcyMDE3NDg5fQ.NJ7gm1aec42kl9YqgMSoXsJk4rFaa5cqecryRsC_Rf4
Content-Type: application/json

{
  "titulo": "Pico Malaga",
  "descripcion": " subir y subir.",
  "fechaInicio": "2026-11-09T09:00:00.000Z",
  "fechaFin": "2026-11-12T11:00:00.000Z",
  "ubicacion": "Alpes",
  "publica": true,
  "participantesmax": 0,
  "imagenes": [
    "https://example.com/img/alp.jpg"
  ],
  "estado": "activa"
}
###Actualizar actividad
PUT http://localhost:3000/api/actividad/13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc3MjE4OTg5MSwiZXhwIjoxNzcyMjc2MjkxfQ.awp1ZPrnPZqPaJoHyJIhgJwfNpd4hlhgKoPNRypFu0A
Content-Type: application/json

{
 "descripcion": "subir, bajar y despues comer"
}
### Finalizar actividad
POST http://localhost:3000/api/actividad/9/finalizar
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjUsImlhdCI6MTc2OTE2NTc2NiwiZXhwIjoxNzY5MTY5MzY2fQ.SG4_eS53Iupr-aXjaXa6a9BB5oPs_oWzZMNCpWW2ZT8

###eliminar actividad
DELETE http://localhost:3000/api/actividad/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjYsImlhdCI6MTc2OTcwODcxMSwiZXhwIjoxNzY5NzEyMzExfQ.MrRu-SwGerxTYjPFH6FfC1UtfB37cB1EGILWPA1p4PQ







#######################USUARIO
### Actualizar usuario
PUT http://localhost:3000/api/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjQsImlhdCI6MTc2OTE2MjgwNiwiZXhwIjoxNzY5MTY2NDA2fQ.mPk0nMxA_YtibLJm38fADBpW3ZrrrMip3TFIPnsQfio
Content-Type: application/json

{
  "nombre": "juan F Modificado",
  "contrasena": "miNuevaPass"
}
### Borrar usuario
DELETE http://localhost:3000/api/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjQsImlhdCI6MTc2OTE2MzE1OSwiZXhwIjoxNzY5MTY2NzU5fQ.RGKRaDof7neN_maM0kkagSYwgE2MAOYJMBEqqAa69b4



#################################################### Participacion
###Crea participacion
POST http://localhost:3000/api/participacion
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTYyNTg4NywiZXhwIjoxNzY5NjI5NDg3fQ.W1uN9dxjduGRHzTcjBmA-0El9sfsT91jh7GlIHpDb0o
Content-Type: application/json

{
  "idActividad": 12
}
###Actualizar el estadoetado juan #eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjUsImlhdCI6MTc2OTE2OTAzNiwiZXhwIjoxNzY5MTcyNjM2fQ.h7rpHS1g9sQT0v6rjTe9zmo9i32ShFNaTt1J-ixCiDY
PUT http://localhost:3000/api/participacion/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjUsImlhdCI6MTc2OTE2OTk2MywiZXhwIjoxNzY5MTczNTYzfQ.yXmUu8AyLALzTAAjhIaY2t5NWgibX6_fkDP6e-slRNw
Content-Type: application/json

{
  "idUsuario": 3,
  "idActividad": 10,
  "aceptada": true
}

### Elimina participacion NO implemantado aun hasta que encontremos una utilidad real
DELETE http://localhost:3000/api/participacion/
Content-Type: application/json

{
  "idUsuario": 3,
  "idActividad": 12
}

######################################Recuerdos

### Crear recuerdo
POST http://localhost:3000/api/recuerdo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjYsImlhdCI6MTc2OTQyNzA5MCwiZXhwIjoxNzY5NDMwNjkwfQ.e4XZkarkfeCxX3nKSJjtVk45IbGthdY7T7RX_1ZZSYE
Content-Type: application/json

{
  "idActividad": 1,
  "titulo": "Gran dia en la montaña",
  "descripcion": "Lo pasamos genial",
  "imagenes": [
    "https://example.com/img/playa1.jpg",
    "https://example.com/img/playa2.jpg"
  ]
}

### Eliminar recuerdo
DELETE http://localhost:3000/api/recuerdo/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjYsImlhdCI6MTc2OTQyNzA5MCwiZXhwIjoxNzY5NDMwNjkwfQ.e4XZkarkfeCxX3nKSJjtVk45IbGthdY7T7RX_1ZZSYE



######################################################## Amistades
### crea amistad
POST http://localhost:3000/api/amistad/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTUzNDcyNSwiZXhwIjoxNzY5NTM4MzI1fQ.7lzW6EbKVySaJYghKOcsHcU6LuNCtZ8fXDGV4CDN0JM
Content-Type: application/json

###Elimina amistad
DELETE http://localhost:3000/api/amistad/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTUzNDcyNSwiZXhwIjoxNzY5NTM4MzI1fQ.7lzW6EbKVySaJYghKOcsHcU6LuNCtZ8fXDGV4CDN0JM
Content-Type: application/json




######################################################## Solicitudes de amistad
### crea solicitud de amistad
POST http://localhost:3000/api/solicitudAmistad/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTUzNDcyNSwiZXhwIjoxNzY5NTM4MzI1fQ.7lzW6EbKVySaJYghKOcsHcU6LuNCtZ8fXDGV4CDN0JM
Content-Type: application/json

###Actualiza solicitud de amistad (aceptar/rechazar)
PUT http://localhost:3000/api/solicitudAmistad/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjYsImlhdCI6MTc2OTUzNDcwNSwiZXhwIjoxNzY5NTM4MzA1fQ.l93Cvmb5ruZQEBWEij2AesuuE-0PpyM3R6VzxhneZPM
Content-Type: application/json

{
  "estado": "aceptada"
}

###Elimina solicitud de amistad
DELETE http://localhost:3000/api/solicitudAmistad/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTUzNDcyNSwiZXhwIjoxNzY5NTM4MzI1fQ.7lzW6EbKVySaJYghKOcsHcU6LuNCtZ8fXDGV4CDN0JM

########################################################Chats y Mensajes
### Crear chat individual
POST http://localhost:3000/api/chatIndividual/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjYsImlhdCI6MTc2OTUzODk5MywiZXhwIjoxNzY5NTQyNTkzfQ.zhJQEgTEI54hb_MLRiRQbmqBgl0h86eKdsP7CmuCBDM
Content-Type: application/json



### Envia mensaje a un chat existente
POST http://localhost:3000/api/mensaje
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjYsImlhdCI6MTc2OTYyNjQ5MCwiZXhwIjoxNzY5NjMwMDkwfQ.obwd13dCY4miq0kal3H04UawqFpIVqLLIbnbhBDMHvQ
Content-Type: application/json

{
  "idChatIndividual": 1,
  "contenido": "Hola, ¿cómo estás hoy 22?"
}

### Elimina mensaje
DELETE http://localhost:3000/api/mensaje/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTYyMTkwOCwiZXhwIjoxNzY5NjI1NTA4fQ.a9J9vm9fIY2sQyb8wmWybHGScolUpeUC299N9wiG5v0


### Actualiza mensaje
PUT http://localhost:3000/api/mensaje/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTYyMTkwOCwiZXhwIjoxNzY5NjI1NTA4fQ.a9J9vm9fIY2sQyb8wmWybHGScolUpeUC299N9wiG5v0
Content-Type: application/json

{
  "contenido": "Hola, ACTUALIZADO?"
}

############################################Chat actividad
### mensaje en chat de actividad
POST http://localhost:3000/api/mensaje
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTYyNTg4NywiZXhwIjoxNzY5NjI5NDg3fQ.W1uN9dxjduGRHzTcjBmA-0El9sfsT91jh7GlIHpDb0o
Content-Type: application/json

{
  "idChatActividad": 10,
  "contenido": "Hola, soy pep"
}

################################ Comentario
### Crear comentario
POST http://localhost:3000/api/comentario
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTY4Mzk4MywiZXhwIjoxNzY5Njg3NTgzfQ.lXRmdgk2DyFKu9x4BtauTjYWDS1Gc14otffwVmdGoI4
Content-Type: application/json

{
  "idRecuerdo": 5,
  "mensaje": "¡mu bueno!"
}
### Eliminar comentario
DELETE http://localhost:3000/api/comentario/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTY4Mzk4MywiZXhwIjoxNzY5Njg3NTgzfQ.lXRmdgk2DyFKu9x4BtauTjYWDS1Gc14otffwVmdGoI4


############################### Megusta
### Crear like a rcuerdo
POST http://localhost:3000/api/likeMegusta
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTY4Mzk4MywiZXhwIjoxNzY5Njg3NTgzfQ.lXRmdgk2DyFKu9x4BtauTjYWDS1Gc14otffwVmdGoI4
Content-Type: application/json

{
  "idComentario": 4
}
### Eliminar like
DELETE http://localhost:3000/api/likeMegusta/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjYsImlhdCI6MTc2OTY4Mzk5NiwiZXhwIjoxNzY5Njg3NTk2fQ.MrIL13SmGEN5Zimwqx_D6YAEY5BXd6NVZM9OwFe4xeM


###################NOtificaciones
### Marcar notificacion como leida
PUT http://localhost:3000/api/notificacion/50
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTY4Mzk4MywiZXhwIjoxNzY5Njg3NTgzfQ.lXRmdgk2DyFKu9x4BtauTjYWDS1Gc14otffwVmdGoI4


### Eliminar notificacion
DELETE http://localhost:3000/api/notificacion/51
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc2OTY4Mzk4MywiZXhwIjoxNzY5Njg3NTgzfQ.lXRmdgk2DyFKu9x4BtauTjYWDS1Gc14otffwVmdGoI4


##############################Crea un tag (administrador)
POST http://localhost:3000/api/tag
Content-Type: application/json

{
  "nombre": "Aventura"
}

###Elimina un tag (administrador)
DELETE http://localhost:3000/api/tag/7

##############################Actividad tag
###Asocia un tag a una actividad
POST http://localhost:3000/api/actividadTag
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjYsImlhdCI6MTc2OTcwODcxMSwiZXhwIjoxNzY5NzEyMzExfQ.MrRu-SwGerxTYjPFH6FfC1UtfB37cB1EGILWPA1p4PQ
Content-Type: application/json

{
  "idActividad": 12,
  "idTag": 6
}

###Desasocia un tag a una actividad
DELETE http://localhost:3000/api/actividadTag
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjYsImlhdCI6MTc2OTcwODcxMSwiZXhwIjoxNzY5NzEyMzExfQ.MrRu-SwGerxTYjPFH6FfC1UtfB37cB1EGILWPA1p4PQ
Content-Type: application/json

{
  "idActividad": 12,
  "idTag": 6
}




#########################Auth
POST http://localhost:3000/api/auth/login/
Content-Type: application/json

{
  "nombre_email": "manuel",
  "contrasena": "hoalpass"
}

###manuel eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjYsImlhdCI6MTc3Mzc0NzYxNiwiZXhwIjoxNzc0NjExNjE2fQ.8f606nSL4Jdg_WEpi8Yvby0KJY81BR0dg7FHmZ9fdPc
### pep eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc3MzEzODk2MCwiZXhwIjoxNzczMjI1MzYwfQ.PNhNszTg6ZWoSMgi9HOX96Pk9wf-C8O4S2iQcdQpsKU


####FONTEND
###manuel localStorage.setItem('token', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjYsImlhdCI6MTc3MzIyNTU5NiwiZXhwIjoxNzc0MDg5NTk2fQ.993cAjbrNsSFxwfhcN-5-96y6NURVQim6vRS-iWbTUs');
###pep localStorage.setItem('token', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc3MzIyNTUwNywiZXhwIjoxNzc0MDg5NTA3fQ.pQgjM4a3BMR0TU-cTsKnzJxEqxGG91fQ4bI8pmIPwzA');

###localStorage.setItem("token", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc3MjUzNzQyNywiZXhwIjoxNzcyNjIzODI3fQ.lifugbBdc69UEa51Ns6Hg12dv2Q8_VnU4Sdpie715gA");



### obtener las actividades de un usuario estando logueado como otro usuario
GET http://localhost:3000/api/actividad/misActividades
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc3MjAxODM3NSwiZXhwIjoxNzcyMDIxOTc1fQ.4wiBmlcQX0KJmatkhQbKPg0tC9rV3VUyUak81duAMb4


### eliminar participacion
DELETE http://localhost:3000/api/participacion/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc3MjY0NTQyMCwiZXhwIjoxNzcyNzMxODIwfQ._BiHYgLpB_kOh4r2Dz_6ylnorPbmK5SMoSz5SMzYkBE
Content-Type: application/json

{
  "idUsuario": 3,
  "idActividad": 16
}

### mostrar usuario 6
GET http://localhost:3000/api/usuario/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc3MjY0NTQyMCwiZXhwIjoxNzcyNzMxODIwfQ._BiHYgLpB_kOh4r2Dz_6ylnorPbmK5SMoSz5SMzYkBE

###Filtrado de actividad



GET http://localhost:3000/api/actividad?tags=Sendero,Deporte


###Añadir un admin a Actividad
PUT http://localhost:3000/api/actividad/admins/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjE0LCJpYXQiOjE3NzU5MDYxODYsImV4cCI6MTc3Njc3MDE4Nn0.9bZ6YvPC0IY6Bmixr5fnHybCl_pGQhp7rBdbZ87x5Kc
Content-Type: application/json

{
  "idAdmin": 13,
  "action": "remove"
}

###Añadir un expulsado a Actividad
PUT http://localhost:3000/api/actividad/expulsados/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc3NTkwNTkyOSwiZXhwIjoxNzc2NzY5OTI5fQ.lLBZtuGWEG0OMONtc9zvl7AhHlVTvaofhRzczKDyoH4
Content-Type: application/json

{
  "idExpulsado": 13,
  "action": "add"
}

### Obtener lista de chats

GET http://localhost:3000/api/chatActividad/chats/mios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjMsImlhdCI6MTc3NzMwNjIyNiwiZXhwIjoxNzc4MTcwMjI2fQ.d2mAux49ir0c-30ebDX5NX50j8YhsnXKd7eGKxvf1ic
